vmware/weathervane

- autoSetup-vmmark.pl
This was the original setup file used for VMmark 3.0.  It is a modification of the autoSetup.pl file.
Signed-off-by: James Zubb jzubb@vmware.com
> Add autoSetup-vmmark.pl script

- autoSetup-vmmark.pl
Signed-off-by: James Zubb <jzubb@vmware.com>
> Update autoSetup-vmmark for Postgres 9.5 support

- weathervane.pl
> Save the original config file and processed command line parameters

- runHarness/RunProcedures/RunProcedure.pm
> bug fixes for RunProcedure cleanupAfterFailure

- dbLoader/src/main/java/com/vmware/weathervane/auction/dbloader/DBLoader.java
- dbLoader/src/main/java/com/vmware/weathervane/auction/dbloader/DbLoaderDao.java
- runHarness/DataManagers/AuctionDataManager.pm
- runHarness/DataManagers/AuctionKubernetesDataManager.pm
> log dbLoader progress messages

- runHarness/RunProcedures/PrepareOnlyRunProcedure.pm
- runHarness/RunProcedures/RunOnlyRunProcedure.pm
> fix RunOnlyRunProcedure with hierarchical log changes

- runHarness/DataManagers/AuctionKubernetesDataManager.pm
- runHarness/Services/AuctionBidKubernetesService.pm
- runHarness/Services/MongodbKubernetesService.pm
- runHarness/Services/NginxKubernetesService.pm
- runHarness/Services/PostgresqlKubernetesService.pm
- runHarness/Services/RabbitmqKubernetesService.pm
- runHarness/Services/TomcatKubernetesService.pm
- runHarness/Services/ZookeeperKubernetesService.pm
(and use version for AuctionKubernetesDataManager)
> use dockerNamespace in generation of kubernetes manifests

- runHarness/Services/MongodbDockerService.pm
- runHarness/Services/NginxDockerService.pm
- runHarness/Services/PostgresqlDockerService.pm
- runHarness/Services/RabbitmqDockerService.pm
- runHarness/Services/TomcatDockerService.pm
- runHarness/Services/ZookeeperDockerService.pm
> Add isStopped implementation for Docker services

- runHarness/ComputeResources/DockerHost.pm
- runHarness/ComputeResources/KubernetesCluster.pm
- runHarness/Parameters.pm
> GetLogs for Docker and Kubernetes now uses --tail with maxLogLines

- runHarness/Parameters.pm
> fix some per-instance parameters usage text

- runHarness/ComputeResources/KubernetesCluster.pm
- runHarness/DataManagers/AuctionKubernetesDataManager.pm
- runHarness/Parameters.pm
- runHarness/RunProcedures/FullRunProcedure.pm
- runHarness/RunProcedures/RunOnlyRunProcedure.pm
- runHarness/RunProcedures/RunProcedure.pm
- runHarness/RunResults/RunResult.pm
- runHarness/Services/KubernetesService.pm
- runHarness/Workload/Workload.pm
- runHarness/WorkloadDrivers/AuctionWorkloadDriver.pm
- weathervane.pl
- workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/core/Run.java
- workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/web/service/RunServiceImpl.java
This pull request contains a number of fixes needed to enable running multiple Workloads.  
It also contains a fix to let weathervane work on a single node cluster, and uses the correct context in the data manager kubectl commands.
> Enable running multiple workloads

- buildDockerImages.pl
- dockerImages/auctionappserverwarmer/Dockerfile
- dockerImages/auctionbidservice/Dockerfile
- dockerImages/auctiondatamanager/Dockerfile
- dockerImages/auctionworkloaddriver/Dockerfile
- dockerImages/cassandra/Dockerfile
- dockerImages/centos7/Dockerfile
- dockerImages/nginx/Dockerfile
- dockerImages/postgresql/Dockerfile
- dockerImages/rabbitmq/Dockerfile
- dockerImages/runharness/Dockerfile
- dockerImages/tomcat/Dockerfile
- dockerImages/zookeeper/Dockerfile
This pull request adds a proxy parameter that allows an http(s) proxy to be specified for the buildDockerImages script.
> Add HTTP Proxy to buildDockerImages script

- auctionAppServerWarmer/src/main/java/com/vmware/weathervane/auction/service/WarmerServiceImpl.java
- configFiles/kubernetes/tomcat.yaml
- runHarness/Parameters.pm
- runHarness/Services/TomcatDockerService.pm
to be consistent with the k8s version which already has the warmer
> add AppServerWarmer for docker only

- runHarness/RunProcedures/FullRunProcedure.pm
- runHarness/RunProcedures/LoadOnlyRunProcedure.pm
- runHarness/RunProcedures/PrepareOnlyRunProcedure.pm
- runHarness/RunProcedures/RunOnlyRunProcedure.pm
- runHarness/RunProcedures/RunProcedure.pm
- runHarness/RunProcedures/StopRunProcedure.pm
> stop tiers sequentially to prevent database corruption issues

- dockerImages/rabbitmq/Dockerfile
- dockerImages/rabbitmq/erlang.repo
> resolves RabbitMQ depenancy failures during setup

- doc/userDocs/usersGuide.md
- runHarness/Parameters.pm
- runHarness/Utils.pm
- runHarness/Workload/Workload.pm
> add prepareConcurrency functionality

- runHarness/ComputeResources/KubernetesCluster.pm
- runHarness/WorkloadDrivers/AuctionKubernetesWorkloadDriver.pm
Collecting kubernetes event log and storing in weathervane/output/<run_num>/0/configuration/clusters/k8sCluster.
> collect k8s events log

- buildDockerImages.pl
Calling docker rmi -f $(docker images -q) and docker container prune -f within cleanupAfterBuild subroutine.
> cleanup after building images

- weathervane.pl
fix problematic syntax that gives errors on some version of perl
> update keys syntax

- runHarness/WorkloadDrivers/AuctionWorkloadDriver.pm
- workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/core/Run.java
undo the changes made with this commit, which broke the sync stopping of multiple workloads:
https://github.com/vmware/weathervane/pull/208/commits/cf2d4a6a6912f1ae2d29db946308ee5fae44f30d
> undo changes that broke the sync stop of multiple workloads

- runHarness/DataManagers/AuctionDataManager.pm
- runHarness/DataManagers/AuctionKubernetesDataManager.pm
- runHarness/Workload/Workload.pm
- runHarness/WorkloadDrivers/AuctionWorkloadDriver.pm
- weathervane.pl
Signed-off-by: Ninad Ingale <ininad@vmware.com>
> Fixed the console log statements to remove the extra spaces from them.

- runHarness/ComputeResources/KubernetesCluster.pm
to fix issue #251 
The kubernetesDeleteAllForCluster subroutine is trying to delete all config maps, failing on OpenShift clusters #251
> use selector in DeleteAllForCluster

- dbLoader/src/main/java/com/vmware/weathervane/auction/dbloader/DbLoaderDao.java
This change addresses the issue with incorrect DB load estimates.
> Improve DB load estimates.
