runHarness/AppInstance/AuctionKubernetesAppInstance.pm, runHarness/DataManagers/DataManager.pm, runHarness/RunProcedures/FullRunProcedure.pm, runHarness/RunProcedures/LoadOnlyRunProcedure.pm, runHarness/RunProcedures/PrepareOnlyRunProcedure.pm, runHarness/RunProcedures/RunOnlyRunProcedure.pm, runHarness/RunProcedures/RunProcedure.pm, runHarness/RunProcedures/StopRunProcedure.pm, runHarness/RunResults/RunResult.pm, runHarness/Services/Service.pm, runHarness/Workload/Workload.pm, runHarness/WorkloadDrivers/AuctionWorkloadDriver.pm, runHarness/WorkloadDrivers/WorkloadDriver.pm, weathervane.pl
WEAT-78 Record Debug Output (send console output to debug log, do not
write debug messages to screen)
WEAT-77 Early failures should still create output logs (send all
console/debug output to $tmpDir)
WEAT-80 Include more console output in console.log (send all console/debug
output to $tmpDir)
use hiearchical output structure - each run procedure creates a new subdir
under $tmpDir
=> make changes for output and debug log issues

runHarness/AppInstance/AppInstance.pm, runHarness/AppInstance/AuctionAppInstance.pm, runHarness/DataManagers/AuctionKubernetesDataManager.pm, runHarness/DataManagers/DataManager.pm, runHarness/Parameters.pm, runHarness/RunManagers/FixedRunManager.pm, runHarness/RunManagers/RunManager.pm, runHarness/RunProcedures/LoadOnlyRunProcedure.pm, runHarness/RunProcedures/PrepareOnlyRunProcedure.pm, runHarness/Services/Service.pm, runHarness/Services/TomcatDockerService.pm, runHarness/WorkloadDrivers/AuctionWorkloadDriver.pm, runHarness/WorkloadDrivers/WorkloadDriver.pm, weathervane.pl
Set weathervaneHome to the current working directory
Adjust use lib for 'runHarness' to be relative to weathervane.pl
Use Parameters.pm default for $tmpDir and make it a constant
Move all relative path adjustments to weathervane.pl
Move logger setup to top of weathervane.pl script
Move help usage code up in weathervane.pl to be more usable
Print run number also with prepareOnly
notes:
There is still usage of /tmp.
Only $tmpDir is a 'fixed' location, but all other config directories are now relative to cwd.
=> Restrict config directories relative to current working directory

runHarness/ComputeResources/KubernetesCluster.pm
This changes kubernetesAreAllPodRunningWithNum so that no check is made for endpoints if there is no service associated with the selector.
=> added check for services in kubernetesAreAllPodRunningWithNum

workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/core/Run.java, workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/core/Workload.java
- The LoadPath uses runStatsHosts, while the statsCollector uses workloadStatsHost
=> Use runStatsHost for loadPath

dockerImages/auctiondatamanager/isDataLoaded.pl, runHarness/DataManagers/AuctionKubernetesDataManager.pm
- The calls to kubectl in AuctionKubernetesDataManager were not using the context defined for the KubernetesCluster, and instead were just getting the current-context from the kubeconfig file.  This fixes that bug.
=> use context in AuctionKubernetesDataManager calls to kubectl

runHarness/ComputeResources/KubernetesCluster.pm, runHarness/WorkloadDrivers/AuctionKubernetesWorkloadDriver.pm
- Rather than using `delete all` when cleaning up after a run, explicitly delete all constructs that might have been created by Weathervane.  Let Kubernetes deleted the pods.  Note that this change issues a delete for some kinds of objects (such as daemonsets) that are not currently used by Weathervane, but that may be in the future.
=> Explicitly delete deployments, etc rather than using all

runHarness/AppInstance/AuctionAppInstance.pm, runHarness/DataManagers/AuctionDataManager.pm, runHarness/Services/CassandraKubernetesService.pm, runHarness/Services/PostgresqlKubernetesService.pm
-There were some leftovers for when postgresql used two volumes.
-And a syntax issue for jvmopts that needs quotes to wrap complicated text.
-also fix a couple of comments for accuracy.
=> fix errors in pl scripts that prevent running with docker

doc/userDocs/usersGuide.md
-In prerequisites, for StorageClass, add text to communicate/clarify that a Provisioner might have a number of required steps that need to be completed before running Weathervane. And, use vSphere Cloud Provider as an example with link.
-In prerequisites, for Perl, note that module Term::ReadKey is required.
-Adjust some quote characters for consistency.
=> doc updates  related to prereqs

auctionApp/src/main/java/com/vmware/weathervane/auction/data/imageStore/ImageStoreFacadeCassandraImpl.java, runHarness/WorkloadDrivers/AuctionWorkloadDriver.pm, workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/core/loadControl/loadPath/FixedLoadPath.java, workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/core/loadControl/loadPath/IntervalLoadPath.java, workloadDriver/src/main/java/com/vmware/weathervane/workloadDriver/common/core/loadControl/loadPath/LoadPath.java, workloadDriver/src/main/resources/logback.xml
- The Interval Run Strategy, which allows varying loads, had not been updated properly for changes from Weathervane 1.0 to 2.0 and did not work properly.  The changes in this pull request fix the interval load path so that it works as in Weathervane 1.0.  Note that this pull request does not update the documentation, so this is still an undocumented and unsupported feature.  The documentation will be updated for the next release once we do more testing with this feature.
- Fixed a bug in the Auction application that resulted in an exception when trying to retrieve a full-sized image for non-current items that do not have full images loaded.
=> Fix Interval Run Strategy

runWeathervane.pl
- Added a check in runWeathervane.pl to make sure that Weathervane can dynamically provision persistent volumes using a PVC for all storage classes.  Note that this check only works for the simple case of the applicationInstanceCluster and storageClasses being defined at the top level (not inside workloads and appInstances).  The more complex cases will be handled later inside the run harness.
=> Check provisioning of PVs in storage classes

runHarness/DataManagers/AuctionKubernetesDataManager.pm
The AuctionDataManager pod takes a large amount of resources (CPU and memory) relative to other pods.  Currently the prepareData process can return before this pod has terminated. This can keep other pods from starting, leading to misleading failedScheduling errors.
The fix is to wait until the pod has terminated before returning.
=> Ensure Datamanager pod is stopped before starting other pods

runWeathervane.pl
Under certain conditions, the output coming from a container doesn't appear in real time in the console. Only after the run completes will the output be displayed.
Previous to this fix: 
@bhoflich suggested to add auto flushing to runWeathervane.pl like already exists in weathervane.pl. This resolves the issue.
With this fix:
Signed-off-by: Rebecca Yo <griderr@vmware.com>
=> Add auto flushing to runWeathervane.pl

configFiles/esxtop/wv.esxtoprc, runHarness/ComputeResources/KubernetesCluster.pm, runHarness/Parameters.pm
- Added a parameter that controls whether `kubectl top` data is collected.  This defaults to false since most clusters don't support this by default.
=> Add parameter to control whether kubectl top is collected

runHarness/ComputeResources/KubernetesCluster.pm
- Previously, when no pod with the appropriate label was found in the method kubernetesExecOne, the process would exit.  This prevented the caller from retrying.  I changed this to return with an error rather than exiting.  I check all of the callers, and they can all handle the error return correctly.
=> Don't exit when pod not found in kubernetesExecOne

buildDockerImages.pl, doc/userDocs/usersGuide.md
wrap docker login username in single quotes to allow special characters
and add line to documentation for : wrap yourUserName in single quotes
=> handle harbor robot names

runWeathervane.pl
This pull request has the following changes:
- It is now possible to override the dockerNamespace from the weathervane config file by specifying it on the command-line to runWeathervane.pl.  Because this is overriding a config file parameter, the parameter must be specified are `--` on the command-line as in: 
`./runWeathervane.pl --configFile=weathervane.config.xsmall -- --dockerNamespace=myNamespace`
=> Enable overriding of dockerNamespace on command-line

dbLoader/src/main/java/com/vmware/weathervane/auction/dbloader/DbLoaderDao.java, runHarness/fixedConfigs.json
increase nginxCacheVolumeSize to 6g for small2-applimit* configurationSizes
shorten db loader update interval to 4 mins to work around 5 min connection inactivity
=> applimit nginx cache 6 g and dbloader interval

testing/Jenkinsfile
Add -f to the docker rmi command to remove all cached images on each build. This will make sure no cached images are being used on build, so any issues in building images will surface.
=> Add force to rmi command to remove all cached images

runHarness/DataManagers/AuctionKubernetesDataManager.pm, runHarness/Factories/WorkloadDriverFactory.pm, runHarness/Workload/Workload.pm, runHarness/WorkloadDrivers/AuctionWorkloadDriver.pm, runHarness/WorkloadDrivers/WorkloadDriver.pm, weathervane.pl
Added a new attribute to WorkloadDriver.pm called workloadCount that keeps track of how many workloads the run has. That attribute was then used to change the output to use either a workload number if there is more than one workload or an empty string if there's only one workload.
I will upload a full run's console output later today.
=> only printing workload number if more than 1 workload

runHarness/fixedConfigs.json
Tested both 150m and 100m two times. Here's how long it took to start the backend services for each one:
**150**
* 17 minutes
* 14 minutes
**100**
* 15 minutes
* 14 minutes
Because both 100m and 150m produced similar results, I changed the appWarmerCpus parameter to 100m.
=> increasing micro app warmer cpus

dockerImages/cassandra/Dockerfile
An update to OpenJDK package results in Cassandra no longer able to deploy:
`Warning Unhealthy 24s (x10 over 9m24s) kubelet Readiness probe failed: nodetool: Failed to connect to '127.0.0.1:7199' - URISyntaxException: 'Malformed IPv6 address at index 7: rmi://[127.0.0.1]:7199'.`
This is an incompatibility between Cassandra and the new OpenJDK version: https://stackoverflow.com/questions/72258217/cassandra-nodetool-urisyntaxexception-malformed-ipv6-address-at-index-7 
Cassandra appears to have been fixed to be compatible with the latest OpenJDK version but we don't expect it will be released until 3.11.15 which we should test at at that time.
We decided to specify the last working version of openjdk for Cassandra until we can update Cassandra to 3.11.15 or use the workaround described at …
=> WEAT-401: Specify OpenJDK for Cassandra image: 1.8.0.322.b06-1.el7_9

dockerImages/cassandra/Dockerfile
See pull request https://github.com/vmware/weathervane/pull/241
This same change is being made to -dev. 
Signed-off-by: Rebecca Yo <griderr@vmware.com>
=> Specify version of openjdk for Cassandra image: 1.8.0.322.b06-1.el7_9

weathervane.pl
- When rampDown is set to 0, it does keep the current run of weathervane in hanging state.
- To prevent this, added a check for rampDown time. We are stopping the current run id rampDown<=0
Signed-off-by: Ninad Ingale <ininad@ininad-a01.vmware.com>
=> Added a Check for the rampDown

dockerImages/cassandra/cassandra.repo
This PR is for fixing the location of Cassandra repo which got moved to : https://cassandra.apache.org/_/download.html
=> Update the location of Cassandra repo
